ns-backup: handle empty list
If the machine does not have a backup, avoid failure like:

  File "/usr/libexec/rpcd/ns.backup", line 161, in <module>
    print(json.dumps({'values': json.loads(completed_process.stdout)}))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Issue #664