fix(migration): remove unused policies
Avoid the following error when there is a conflict of names:

Traceback (most recent call last):
  File "/usr/share/ns-migration/20wan", line 89, in <module>
    mwan.store_policy(u, f'{pname[0:6]}_only', [i])
  File "/usr/lib/python3.11/site-packages/nethsec/mwan/__init__.py", line 257, in store_policy
nethsec.utils.ValidationError: ('name', 'unique', 'timene_only')